"""updated flight table

Revision ID: 112c02b6b50d
Revises: 9e1a81cf0ee7
Create Date: 2025-03-13 11:45:11.552421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '112c02b6b50d'
down_revision: Union[str, None] = '9e1a81cf0ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('departure_date_time', sa.DateTime(), nullable=False))
    op.add_column('flights', sa.Column('arrival_date_time', sa.DateTime(), nullable=False))
    op.drop_column('flights', 'arrival_date')
    op.drop_column('flights', 'departure_time')
    op.drop_column('flights', 'arrival_time')
    op.drop_column('flights', 'departure_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('departure_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('arrival_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('departure_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('arrival_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('flights', 'arrival_date_time')
    op.drop_column('flights', 'departure_date_time')
    # ### end Alembic commands ###
