"""fixed participant table

Revision ID: 16bbb30d5f74
Revises: 4e0eb4ff99f1
Create Date: 2025-03-13 11:32:55.585837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16bbb30d5f74'
down_revision: Union[str, None] = '4e0eb4ff99f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'user_id')
    # ### end Alembic commands ###
