"""added name, address, capacity to accommodation

Revision ID: 1735dfb6a3af
Revises: d3f9e759e557
Create Date: 2025-03-26 10:45:47.437610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1735dfb6a3af'
down_revision: Union[str, None] = 'd3f9e759e557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('accommodation', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('accommodation', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accommodation', 'capacity')
    op.drop_column('accommodation', 'address')
    op.drop_column('accommodation', 'name')
    # ### end Alembic commands ###
