"""added train table

Revision ID: 19a37a40a96a
Revises: 16bbb30d5f74
Create Date: 2025-03-13 11:36:44.351476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '19a37a40a96a'
down_revision: Union[str, None] = '16bbb30d5f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('from_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('departure_date_time', sa.Date(), nullable=False),
    sa.Column('arrival_date_time', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trains')
    # ### end Alembic commands ###
