"""added participant table

Revision ID: 627bbad6a70c
Revises: 680db1e73fd0
Create Date: 2025-03-13 11:21:15.295363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '627bbad6a70c'
down_revision: Union[str, None] = '680db1e73fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favorite_accommodation', sa.Column('participant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorite_accommodation', 'participants', ['participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_accommodation', type_='foreignkey')
    op.drop_column('favorite_accommodation', 'participant_id')
    op.drop_table('participants')
    # ### end Alembic commands ###
