"""added flight table

Revision ID: 9e1a81cf0ee7
Revises: 19a37a40a96a
Create Date: 2025-03-13 11:44:20.652268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e1a81cf0ee7'
down_revision: Union[str, None] = '19a37a40a96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('flight_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###
