"""removed optional field on name, address, capacity from accommodation table

Revision ID: 9e5fa78391fb
Revises: 9064ee90038e
Create Date: 2025-03-26 10:56:55.211244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e5fa78391fb'
down_revision: Union[str, None] = '9064ee90038e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accommodation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accommodation', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accommodation', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accommodation', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accommodation', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accommodation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
