"""added optional name, address, capacity to accommodation

Revision ID: a30fd841a1c1
Revises: 1735dfb6a3af
Create Date: 2025-03-26 10:53:29.761023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a30fd841a1c1'
down_revision: Union[str, None] = '1735dfb6a3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('accommodation', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('accommodation', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accommodation', 'capacity')
    op.drop_column('accommodation', 'address')
    op.drop_column('accommodation', 'name')
    # ### end Alembic commands ###
